import time
from typing import TYPE_CHECKING

from app.utils.tokens import estimate_tokens

if TYPE_CHECKING:
    from app.ai.model_gateway import ModelResponse


class DemoLocalProvider:
    provider_name = "demo-local"
    model = "deterministic-rag-demo"
    is_configured = True

    async def chat_completion(
        self,
        *,
        messages: list[dict],
        temperature: float,
        max_tokens: int,
        metadata: dict,
    ) -> "ModelResponse":
        from app.ai.model_gateway import ModelResponse

        started = time.perf_counter()
        question = next((message.get("content", "") for message in reversed(messages) if message.get("role") == "user"), "")
        context = metadata.get("context", "")
        trimmed = str(context or "No retrieved context was available.").strip()[:1200]
        content = (
            f"Based on the indexed workspace documents, here is the most relevant answer to: \"{question}\".\n\n"
            f"{trimmed}\n\n"
            "This response is generated by the clearly labeled demo-local provider. Configure DeepSeek or Qwen keys "
            "to replace this deterministic demo answer with a live model call."
        )
        prompt_tokens = sum(estimate_tokens(str(message.get("content", ""))) for message in messages)
        completion_tokens = estimate_tokens(content)
        return ModelResponse(
            provider=self.provider_name,
            model=self.model,
            content=content,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            latency_ms=int((time.perf_counter() - started) * 1000),
            raw_metadata={"temperature": temperature, "max_tokens": max_tokens},
        )
